[package]
name = "ormcle"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["ormcle_core", "ormcle_macro"]

[dependencies]
sibyl = { version = "0.6.22" }
tokio = { version = "1.48.0", optional = true }
ormcle_macro = { path = "./ormcle_macro"}

[features]
blocking = ["sibyl/blocking"]
nonblocking = ["sibyl/nonblocking"]
tokio = ["nonblocking", "tokio/rt-multi-thread", "sibyl/tokio"]
actix  = ["nonblocking", "sibyl/actix"]
